export type Unit = {
  unitNumber: number;
  description: string;
  backgroundColor: `bg-${string}`;
  textColor: `text-${string}`;
  borderColor: `border-${string}`;
  tiles: Tile[];
};

export type Tile =
  | {
      type: "star" | "dumbbell" | "book" | "trophy" | "fast-forward";
      description: string;
    }
  | { type: "treasure" };

export type TileType = Tile["type"];

export const units: readonly Unit[] = [
  {
    unitNumber: 1,
    description: "Gente que estudia español",
    backgroundColor: "bg-[#58cc02]",
    textColor: "text-[#58cc02]",
    borderColor: "border-[#46a302]",
    tiles: [
      {
        type: "star",
        description: "Hablamos de los intereses en el español",
      },
      {
        type: "book",
        description: "Nombres y apellidos",
      },
      {
        type: "star",
        description: "El español en el mundo",
      },
      { type: "treasure" },
      { type: "book", description: "Mis intereses" },
      { type: "trophy", description: "Unit 1 review" },
    ],
  },
  {
    unitNumber: 2,
    description: "Gente con gente",
    backgroundColor: "bg-[#ce82ff]",
    textColor: "text-[#ce82ff]",
    borderColor: "border-[#a568cc]",
    tiles: [
      { type: "fast-forward", description: "Hablar con otras personas" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Cómo presentarse" },
      { type: "treasure" },
      { type: "star", description: "Expresar opiniones" },
      { type: "book", description: "Hacer amigos" },
      { type: "star", description: "Invitaciones" },
      { type: "book", description: "Planes sociales" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "trophy", description: "Unit 2 review" },
    ],
  },
  {
    unitNumber: 3,
    description: "Gente de vacaciones",
    backgroundColor: "bg-[#00cd9c]",
    textColor: "text-[#00cd9c]",
    borderColor: "border-[#00a47d]",
    tiles: [
      { type: "fast-forward", description: "Hablar de vacaciones" },
      { type: "book", description: "Destinos turísticos" },
      { type: "star", description: "Organizar un viaje" },
      { type: "treasure" },
      { type: "book", description: "Transporte y alojamiento" },
      { type: "star", description: "Actividades de ocio" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Las vacaciones ideales" },
      { type: "trophy", description: "Unit 3 review" },
    ],
  },
  {
    unitNumber: 4,
    description: "Gente de compras",
    backgroundColor: "bg-[#ff5733]",
    textColor: "text-[#ff5733]",
    borderColor: "border-[#c70039]",
    tiles: [
      { type: "fast-forward", description: "Hablar de compras" },
      { type: "book", description: "Ropa y accesorios" },
      { type: "star", description: "Tiendas y mercados" },
      { type: "treasure" },
      { type: "book", description: "Precios y ofertas" },
      { type: "star", description: "Hacer una lista de compras" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Las mejores compras" },
      { type: "trophy", description: "Unit 4 review" },
    ],
  },
  {
    unitNumber: 5,
    description: "Gente en forma",
    backgroundColor: "bg-[#ffb833]",
    textColor: "text-[#ffb833]",
    borderColor: "border-[#ff7f50]",
    tiles: [
      { type: "fast-forward", description: "Hablar de la salud y el ejercicio" },
      { type: "book", description: "Dieta y nutrición" },
      { type: "star", description: "Deportes y actividades físicas" },
      { type: "treasure" },
      { type: "book", description: "El bienestar" },
      { type: "star", description: "Consejos para mantenerse en forma" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Mi rutina de ejercicio" },
      { type: "trophy", description: "Unit 5 review" },
    ],
  },
  {
    unitNumber: 6,
    description: "Gente que come bien",
    backgroundColor: "bg-[#28a745]",
    textColor: "text-[#28a745]",
    borderColor: "border-[#218838]",
    tiles: [
      { type: "fast-forward", description: "Hablar de la comida" },
      { type: "book", description: "Recetas y cocina" },
      { type: "star", description: "Comer en restaurantes" },
      { type: "treasure" },
      { type: "book", description: "Los platos típicos" },
      { type: "star", description: "Consejos de alimentación" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Mis comidas favoritas" },
      { type: "trophy", description: "Unit 6 review" },
    ],
  },
  {
    unitNumber: 7,
    description: "Gente que trabaja",
    backgroundColor: "bg-[#007bff]",
    textColor: "text-[#007bff]",
    borderColor: "border-[#0056b3]",
    tiles: [
      { type: "fast-forward", description: "Hablar del trabajo" },
      { type: "book", description: "Profesiones y oficios" },
      { type: "star", description: "El ambiente laboral" },
      { type: "treasure" },
      { type: "book", description: "Buscar empleo" },
      { type: "star", description: "Entrevistas de trabajo" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Mis experiencias laborales" },
      { type: "trophy", description: "Unit 7 review" },
    ],
  },
  {
    unitNumber: 8,
    description: "Gente que viaja",
    backgroundColor: "bg-[#6f42c1]",
    textColor: "text-[#6f42c1]",
    borderColor: "border-[#5a30a1]",
    tiles: [
      { type: "fast-forward", description: "Hablar de viajes" },
      { type: "book", description: "Planificación de viajes" },
      { type: "star", description: "Medios de transporte" },
      { type: "treasure" },
      { type: "book", description: "Experiencias de viaje" },
      { type: "star", description: "Consejos para viajar" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Mis viajes favoritos" },
      { type: "trophy", description: "Unit 8 review" },
    ],
  },
  {
    unitNumber: 9,
    description: "Gente de ciudad",
    backgroundColor: "bg-[#17a2b8]",
    textColor: "text-[#17a2b8]",
    borderColor: "border-[#138496]",
    tiles: [
      { type: "fast-forward", description: "Hablar de la vida en la ciudad" },
      { type: "book", description: "Lugares en la ciudad" },
      { type: "star", description: "Actividades urbanas" },
      { type: "treasure" },
      { type: "book", description: "Problemas urbanos" },
      { type: "star", description: "Soluciones urbanas" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Mi ciudad favorita" },
      { type: "trophy", description: "Unit 9 review" },
    ],
  },
  {
    unitNumber: 10,
    description: "Gente y fechas",
    backgroundColor: "bg-[#dc3545]",
    textColor: "text-[#dc3545]",
    borderColor: "border-[#c82333]",
    tiles: [
      { type: "fast-forward", description: "Hablar de eventos históricos" },
      { type: "book", description: "Fechas importantes" },
      { type: "star", description: "Acontecimientos históricos" },
      { type: "treasure" },
      { type: "book", description: "Figuras históricas" },
      { type: "star", description: "Lugares históricos" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Mis eventos históricos favoritos" },
      { type: "trophy", description: "Unit 10 review" },
    ],
  },
  {
    unitNumber: 11,
    description: "Gente en casa",
    backgroundColor: "bg-[#ffc107]",
    textColor: "text-[#ffc107]",
    borderColor: "border-[#e0a800]",
    tiles: [
      { type: "fast-forward", description: "Hablar de la vida en casa" },
      { type: "book", description: "La casa y el hogar" },
      { type: "star", description: "Actividades domésticas" },
      { type: "treasure" },
      { type: "book", description: "Los quehaceres" },
      { type: "star", description: "Hacer una lista de tareas" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Mi casa ideal" },
      { type: "trophy", description: "Unit 11 review" },
    ],
  },
  {
    unitNumber: 12,
    description: "Gente e historias",
    backgroundColor: "bg-[#343a40]",
    textColor: "text-[#343a40]",
    borderColor: "border-[#23272b]",
    tiles: [
      { type: "fast-forward", description: "Hablar de historias y relatos" },
      { type: "book", description: "Contar una historia" },
      { type: "star", description: "Narrar eventos" },
      { type: "treasure" },
      { type: "book", description: "Personajes históricos" },
      { type: "star", description: "Hechos y circunstancias" },
      { type: "treasure" },
      { type: "dumbbell", description: "Personalized practice" },
      { type: "book", description: "Mi historia favorita" },
      { type: "trophy", description: "Unit 12 review" },
    ],
  },
];
